In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv("D:\\desktop\\ML\\DATA\\50_Startups.csv")
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
dataset['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [6]:
dataset = pd.get_dummies(dataset, columns=['State'])

In [7]:
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_California,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,False,True
1,162597.70,151377.59,443898.53,191792.06,True,False,False
2,153441.51,101145.55,407934.54,191050.39,False,True,False
3,144372.41,118671.85,383199.62,182901.99,False,False,True
4,142107.34,91391.77,366168.42,166187.94,False,True,False

In [8]:
dataset = dataset.drop(['State_California'], axis=1)

In [9]:
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False

In [10]:
# split the data into indep and dep
x = dataset.drop(['Profit'], axis=1)
y = dataset[['Profit']]

In [11]:
x.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False

In [12]:
y.head()

      Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [13]:
# pls handle outlier if you compare with linear regression
# split the data into training and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

# Building Model - DecisionTree Regression Model

In [15]:
from sklearn.tree import DecisionTreeRegressor
dtree = DecisionTreeRegressor()
dtree.fit(x_train, y_train)

DecisionTreeRegressor()

In [16]:
y_pred_train = dtree.predict(x_train)
y_pred_test = dtree.predict(x_test)

In [17]:
# Evaluate the model
from sklearn.metrics import r2_score

In [18]:
print(r2_score(y_train, y_pred_train))
print()
print(r2_score(y_test, y_pred_test))

1.0

0.933711949151281

# Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(x_train, y_train)

LinearRegression()

In [21]:
y_pred_train = linear.predict(x_train)
y_pred_test = linear.predict(x_test)

In [22]:
print(r2_score(y_train, y_pred_train))
print()
print(r2_score(y_test, y_pred_test))

0.9511705268907698

0.931581519915206

# Random Forest Regression

In [24]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(x_train, y_train)

C:\Users\PANKAJ SHARMA\AppData\Local\Temp\ipykernel_54516\3063819375.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train, y_train)

RandomForestRegressor()

In [25]:
y_pred_train = rf.predict(x_train)
y_pred_test = rf.predict(x_test)

In [26]:
print(r2_score(y_train, y_pred_train))
print()
print(r2_score(y_test, y_pred_test))

0.9870114284509579

0.949398180378603