In [1]:
import os
import numpy as np
import pandas as pd
import sys

In [2]:
print(pd.__version__)
print(np.__version__)

2.3.3
1.26.4

In [3]:
print(sys.executable)

C:\Users\PANKAJ SHARMA\anaconda3\envs\ml_clean\python.exe

In [4]:
df = pd.read_csv(r"D:\desktop\ML\Machine Learning\Supervised ML\Naive bayes\SMSSpamCollection", sep='\t')
df

,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
0,ham,Ok lar... Joking wif u oni...
1,spam,Free entry in 2 a wkly comp to win FA Cup fina...
2,ham,U dun say so early hor... U c already then say...
3,ham,"Nah I don't think he goes to usf, he lives aro..."
4,spam,FreeMsg Hey there darling it's been 3 week's n...
...,...,...
5566,spam,This is the 2nd time we have tried 2 contact u...
5567,ham,Will ü b going to esplanade fr home?
5568,ham,"Pity, * was in mood for that. So...any other s..."
5569,ham,The guy did some bitching but I acted like i'd...
5570,ham,Rofl. Its true to its name

In [5]:
df = pd.read_csv(r"D:\desktop\ML\Machine Learning\Supervised ML\Naive bayes\SMSSpamCollection", sep='\t',names =["Label", "Messages"])
df

     Label                                           Messages
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
df.isnull().sum()

Label       0
Messages    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Label     5572 non-null   object
 1   Messages  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [8]:
df['Label'].nunique()

2

In [9]:
#df['Label'].value_counts()/len(df)*100
df['Label'].value_counts()

Label
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
ham = df[df['Label']=='ham']
spam = df[df['Label']=='spam']

In [11]:
print(ham.shape, spam.shape)

(4825, 2) (747, 2)

In [12]:
# Upsample minority class, This is oversampling the minority class
spam = spam.sample(ham.shape[0], replace=True)

In [13]:
print(ham.shape, spam.shape)

(4825, 2) (4825, 2)

In [14]:
data = pd.concat([ham, spam], ignore_index=True)
data.shape

(9650, 2)

# Shuffle After Concatenation (Very Important)
- Right now:
- All ham rows first
- All spam rows later
- Model may see structured ordering.

In [15]:
data = data.sample(frac=1, random_state=42).reset_index(drop=True)
# .sample()? It randomly selects rows from a DataFrame.
# frac=1 means take 100% of rows,but in random order

In [16]:
data.head()

  Label                                           Messages
0   ham            So what about you. What do you remember
1   ham  My life Means a lot to me, Not because I love ...
2   ham  E admin building there? I might b slightly ear...
3   ham               Sorry, went to bed early, nightnight
4  spam  You have 1 new voicemail. Please call 08719181...

In [17]:
data['Label'].value_counts()

Label
ham     4825
spam    4825
Name: count, dtype: int64

# Data Cleaning part

In [18]:
# pip install nltk
import re
import nltk
nltk.download('stopwords')
# stopwords: nltk.download('stopwords')
# punkt : nltk.download('punkt')
# wordnet:nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\PANKAJ
[nltk_data]     SHARMA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
corpus = []

for text in data['Messages']:
    review = re.sub('[^a-zA-Z]',' ', text)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stop_words]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['rememb',
 'life mean lot love life love peopl life world call friend call world ge',
 'e admin build might b slightli earlier call u reach',
 'sorri went bed earli nightnight',
 'new voicemail pleas call',
 'urgent mobil number award prize guarante call land line claim valid hr ppm',
 'camera award sipix digit camera call fromm landlin deliveri within day',
 'nice day impress sensibl went home earli feel fine bore rememb',
 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max',
 'kindli send one flat lt decim gt today',
 'hey darlin pick u colleg u tell wen mt love pete xx',
 'mobil club choos top qualiti item mobil cfca',
 'fyi gonna call sporad start like lt gt bc doin shit',
 'realli tot ur paper end long ago wat u copi ju got use u happi lar still haf studi',
 'know pl open back',
 'wake sinc check stuff saw true avail space pl call embassi send mail',
 'jokin lar depend phone father get lor',
 'hi ami send free phone number coupl day give access adult parti',
 'today offer claim ur worth discount voucher text ye savamob member offer mobil cs sub unsub repli x',
 'hi jon pete ive bin spain recent hav sum dinero left bill said u ur rent mayb interest hav pe around tb jame',
 'accordingli repeat text word ok mobil phone send',
 'bloomberg messag center wait appli futur http career bloomberg com',
 'costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'poor girl go one day lmao',
 'new textbuddi chat horni guy ur area p free receiv search postcod gaytextbuddi com txt one name',
 'record indic u mayb entitl pound compens accid claim free repli claim msg stop txt stop',
 'tkt euro cup final cash collect call b pobox ppm',
 'forward hi mailbox messag sm alert match pleas call back retriev messag match cc p min',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'hot n horni will live local text repli hear strt back p per msg netcollex ltdhelpdesk repli stop end',
 'send naughti pix',
 'say bold torch later one torch bold',
 'meet da call',
 'welcom uk mobil date msg free give free call futur mg bill p daili cancel send go stop',
 'lip sync shangela',
 'urgent tri contact u today draw show prize guarante call land line claim j po box c pm',
 'nokia tone ur mob everi week txt nok st tone free get txtin tell ur friend p tone repli hl info',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'peopl dog area call join like mind guy arrang even minapn ls bb',
 'awesom text restock',
 'take derek amp taylor walmart back time done leav mous desk text priscilla readi',
 'oh k placement ah',
 'yeah sure thing mate haunt got stuff sort im go sound anyway promot hex way dont know number joke',
 'took hooch walk toaday fell splat graze knee everyth stay home see tomorrow',
 'haha think',
 'come onlin today night',
 'rington club gr new poli direct mobil everi week',
 'home n readi',
 'somewher beneath pale moon light someon think u dream come true goodnit amp sweet dream',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'good luck draw take place th feb good luck remov send stop custom servic',
 'rock yr chik get filthi film xxx pic yr phone rpli filth saristar ltd e yt p per day stop cancel',
 'let know need anyth els salad desert someth mani beer shall get',
 'urgent pleas call landlin complimentari lux costa del sol holiday cash await collect ppm sae cs jame eh rr',
 'miss',
 'next amaz xxx picsfre video sent enjoy one vid enough day text back keyword picsfre get next video',
 'hello thanx take call got job start monday',
 'way',
 'motiv behind everi dark shine light wait find behind everi best friend alway trust love bslvyl',
 'phoni award today voda number end xxxx select receiv award match pleas call quot claim code standard rate app',
 'guarante cash prize claim yr prize call custom servic repres pm cost p',
 'bear pic nick tom pete dick fact type tri gay chat photo upload call p min stop text call',
 'love night wake see messag hope smile know great morn',
 'import inform orang user xxxxxxx today lucki day find log onto http www urawinn com fantast surpris await',
 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p',
 'rgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max',
 'cant pick phone right pl send messag',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'otherwis part time job na tuition',
 'k best congrat',
 'new messag call',
 'urgent ur guarante award still unclaim call closingd claimcod pmmorefrommobil bremov mobypobox ls yf',
 'babe lost',
 'nope sinc ayo travel forgotten guy',
 'urgent import inform user today lucki day find log onto http www urawinn com fantast surpris await',
 'forward pleas call immedi urgent messag wait',
 'abl sleep',
 'free tarot text find love life tri free text chanc free msg',
 'sir wait call',
 'hope pee burn tonit',
 'bore housew chat n date bt nation rate p min landlin',
 'safe trip nigeria wish happi soon compani share moment',
 'today offer claim ur worth discount voucher text ye savamob member offer mobil cs sub unsub repli x',
 'alright see bit',
 'pl send comprehens mail pay much',
 'tag friend seem count friend',
 'free entri weekli comp send word enter c www textcomp com cust care',
 'goodmorn grandfath expir leav today',
 'r u sam p eachoth meet go hous',
 'oki',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'custom place call',
 'ok',
 'nah think goe usf live around though',
 'check choos babe video sm shsex netun fgkslpopw fgkslpo',
 'dear u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr',
 'free text messag valid decemb',
 'sm ac jsco energi high u may know channel day ur leadership skill r strong psychic repli an w question end repli end jsco',
 'k k pa lunch aha',
 'k leav soon littl',
 'lt gt min stop somewher first',
 'loan purpos homeown tenant welcom previous refus still help call free text back help',
 'win shop spree everi week start play text store skilgm tsc winawk age perweeksub',
 'check head drop stuff',
 'urgent call landlin complimentari ibiza holiday cash await collect sae cs po box sk wp ppm',
 'hard live chat p min choos girl connect live call cheap chat uk biggest live servic vu bcm wc n xx',
 'thank love torch bold',
 'time ur flight tmr',
 'warner villag c colin farrel swat wkend warner villag get free med popcorn show msg ticket kiosk valid c c kiosk repli soni mre film offer',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'beauti truth graviti read care heart feel light someon feel heavi someon leav goodmorn',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'u r subscrib textcomp wkli comp st wk free question follow subsequ wk charg p msg unsubscrib txt stop custcar',
 'boo thing back home littl bore alreadi',
 'win year suppli cd store ur choic worth enter weekli draw txt music ts cs www ldew com sub win ppmx',
 'gr poli tone mob direct u rpli poli titl eg poli breath titl crazyin sleepingwith finest ymca getz co uk pobox w wq p',
 'oh god found number glad text back xafter msg cst std ntwk chg',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg txtauction',
 'gimm lt gt minut ago',
 'nd time tri contact u u pound prize claim easi call p per minut bt nation rate',
 'howz pain hope u r fine',
 'k sure consent form v',
 'dare chang ring',
 'turn stereo love mi phone unknown album',
 'free st week nokia tone ur mob everi week txt nokia get txting tell ur mate zed pobox w wq norm p tone',
 'differ style',
 'that cool want pleas',
 'free unlimit hardcor porn direct mobil txt porn get free access hr chrgd p per day txt stop exit msg free',
 'jay told alreadi',
 'saturday sunday holiday difficult',
 'send content page',
 'account credit free text messag activ txt word credit cs www biz',
 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate',
 'surf onlin store offer want buy thing',
 'guarante cash prize claim yr prize call custom servic repres pm cost p',
 'go take bath ill place key window',
 'nd attempt contract u week top prize either cash prize call',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg txtauction',
 'thank rington order refer number x mobil charg tone arriv pleas call custom servic colour red text colour txtstar',
 'surli ill give come review',
 'shop till u drop either k k cash travel voucher call ntt po box cr bt fixedlin cost ppm mobil vari',
 'wherr boytoy',
 'want new video phone anytim network min half price line rental free text month repli call free deliveri',
 'didnt complet gist oh',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'hey babe go ever figur go new year',
 'goal arsen henri v liverpool henri score simpl shot yard pass bergkamp give arsen goal margin min',
 'wife knew time murder exactli',
 'hi ibh custom loyalti offer new nokia mobil txtauction txt word start get',
 'want new nokia colour phone deliv tomorrow free minut mobil free text free camcord repli call',
 'twink bear scalli skin jock call miss weekend fun call p min stop text call nat rate',
 'go write msg put dictionari mode cover screen hand press lt gt gentli remov ur hand interest',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'u nokia plu free digit camera u get u win free auction take part send nokia pobox tcr w',
 'swhrt u dey hope ur ok tot u day love n miss take care',
 'bore speed date tri speedchat txt speedchat like em txt swap get new chatter chat pobox w wq p msg rcd',
 'ur chanc win wkli shop spree txt shop c www txt shop com custcar x p wk',
 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate',
 'siva hostel aha',
 'v skint fanci bevi waz gona go meet othr spoon jst bin watchng planet earth sofa v comfey dont make hav gd night',
 'network allow compani bill sm respons supplier shop give guarante sell b g',
 'want anytim network min text new video phone five pound per week call repli deliveri tomorrow',
 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'could seen recognis face',
 'hot live fantasi call p per min ntt ltd po box croydon cr wb nation rate call',
 'free day sexi st georg day pic jordan txt pic dont miss everi wk sauci celeb pic c pocketbab co uk wk',
 'fran decid go n e way im complet broke knacker got bout c u mrw love janx p dad fone credit',
 'master buy bb co sale bf',
 'dont use hook',
 'sell ton coin sell coin someon thru paypal voila money back life pocket',
 'date servic ask contact u someon shi call reveal pobox uz p',
 'anyway go gym whatev love smile hope ok good day babe miss much alreadi',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'dhoni luck win big titl win',
 'made eta taunton plan hope still okday good see xx',
 'eastend tv quiz flower dot compar violet e tulip f lili txt e f chanc win cash wkent p',
 'im good think',
 'oki',
 'ft good combin',
 'pick receipt someth earlier',
 'realli need kiss u miss u babi ur babi eva',
 'urgent mobil award bonu caller prize nd attempt contact call box qu',
 'sunshin quiz wkli q win top soni dvd player u know countri liverpool play mid week txt ansr sp tyron',
 'mobil mth updat free orang latest colour camera mobil unlimit weekend call call mobil upd freefon stoptxt',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'even friend priest call',
 'uncl abbey happi new year abiola',
 'pleas protect e threat sib never ask sensit inform like password atm sm pin thru email never share password anybodi',
 'hi happi birthday hi hi hi hi hi hi hi',
 'remind download content alreadi paid goto http doit mymobi tv collect content',
 'lord ring return king store repli lotr june chanc win lotr soundtrack cd stdtxtrate repli stop end txt',
 'cashbin co uk get lot cash weekend www cashbin co uk dear welcom weekend got biggest best ever cash give away',
 'tri call repli sm video mobil min unlimit text free camcord repli call',
 'hey charl sorri late repli',
 'current messag await collect collect messag call',
 'yup havent want go yoga call book',
 'yet chikku go room nw bu',
 'yeah leav coupl minut amp let know get mu',
 'urgent pleas call landlin abta complimentari tenerif holiday cash await collect sae cs box cw wx ppm',
 'much buzi',
 'privat account statement show un redeem point call identifi code expir',
 'next amaz xxx picsfre video sent enjoy one vid enough day text back keyword picsfre get next video',
 'prepar pound everi night',
 'told hr want post chennai work',
 'loan purpos homeown tenant welcom previous refus still help call free text back help',
 'sex ur mobil free sexi pic jordan text babe everi wk get sexi celeb pocketbab co uk pic wk',
 'loan purpos homeown tenant welcom previous refus still help call free text back help',
 'head straight',
 'send resum',
 'ard like dat lor juz meet mrt station dun haf come',
 'dear u invit xchat final attempt contact u txt chat',
 'hope good week check',
 'sm servic inclus text credit pl goto www comuk net login qxj unsubscrib stop extra charg help comuk cm ae',
 'pay first lar da stock comin',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'u look da lib got stuff havent finish yet',
 'reciev tone within next hr term condit pleas see channel u teletext pg',
 'hi ya babe x u goten bout scammer get smart though regular vodafon respond get prem rate msg subscript no use also bewar',
 'releas anoth italian one today cosign option',
 'pleas call custom servic repres pm guarante cash prize',
 'guarante cash prize claim yr prize call custom servic repres pm',
 'u haf keep busi',
 'kit strip bill p netcollex ltd po box ig oja',
 'yep great loxahatche xma tree burn lt gt start hour',
 'well watch shrek b',
 'congrat mobil g videophon r call videochat wid ur mate play java game dload polyh music nolin rentl bx ip pm',
 'natalja f invit friend repli ye see www sm ac u nat stop send stop frnd',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'privat account statement show un redeem point call identifi code expir',
 'last chanc claim ur worth discount voucher today text shop savamob offer mobil cs savamob pobox uz sub',
 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max',
 'block breaker come delux format new featur great graphic mobil buy repli get bbdelux take challeng',
 'win cash prize prize worth',
 'urgent tri contact u today draw show prize guarante call land line claim valid hr',
 'guarante cash prize claim yr prize call custom servic repres pm cost p',
 'hi chachi tri call u unabl reach u pl give miss cal u c tiz msg kanagu',
 'lost help',
 'free tone hope enjoy new content text stop unsubscrib help p provid tone co uk',
 'dear xxxxxxx u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr',
 'send yetti number pl',
 'pleas call amanda regard renew upgrad current mobil handset free charg offer end today tel subject c',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'custom loyalti offer new nokia mobil txtauction txt word start get ctxt tc p mtmsg',
 'sent send',
 'remain unconvinc elabor test willpow',
 'ye last practic',
 'ok happen behav like',
 'themob hit link get premium pink panther game new sugabab crazi zebra anim badass hoodi wallpap free',
 'hello r u im bore inev thought id get bore tv tell someth excit happen anyth',
 'still mayb leav credit card get ga get back like told',
 'cmon babe make horni turn txt fantasi babe im hot sticki need repli cost cancel send stop',
 'never believ actual got taunton wow',
 'anyth lor u decid',
 'alway chat fact need money rais',
 'yeah probabl still gotta check leo',
 'opinion jada kusruthi lovabl silent spl charact matur stylish simpl pl repli',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'new tone week includ mcfli ab sara jorg shock smith switch order follow instruct next messag',
 'see finish load loan pay',
 'uniqu user id remov send stop custom servic',
 'marri local women look discreet action real match instantli phone text match msg cost p stop txt stop bcmsfwc n xx',
 'ok would b love u r sure think wot u want drinkin dancin eatin cinema u wot',
 'privat account statement show un redeem point call identifi code expir',
 'room',
 'wan win meet greet westlif u current tour unbreak untam unkempt text cost p std text',
 'sac score big hundr set batsman',
 'free st week entri textpod chanc win gb ipod cash everi wk txt pod ts cs www textpod net custcar',
 'say lt gt year old man money last lt gt still wait check',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'know result',
 'nah perpetu dd',
 'great role model give much realli wish day miracl god reason everyth must say wish knew dont look sinc young still great day',
 'go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'chang fb jaykwon thuglyf falconerf',
 'love start attract feel need everi time around first thing come thought would start day end everi time dream love everi breath name life happen around life name would cri give happi take sorrow readi fight anyon love craziest thing love proov anyon girl beauti ladi whole planet alway sing prais love start make chicken curri end maki sambar life beauti get everi morn thank god day would like say lot tell later',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'come peopl',
 'haha figur well found piec priscilla bowl',
 'dunno juz askin co got card got salon call hair sens tot da one cut ur hair',
 'shop till u drop either k k cash travel voucher call ntt po box cr bt fixedlin cost ppm mobil vari',
 'freemsg txt call claim reward hour talk time use phone subscrib gbp mnth inc hr stop txtstop',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'lol well without could big sale togeth',
 'want new nokia colour phone deliveredtomorrow free minut mobil free text free camcord repli call',
 'dunno lei thk mum lazi go neva ask yet',
 'hey elain today meet still',
 'dunno lei like dun haf',
 'themob yo yo yo come new select hot download member get free click open next link sent ur fone',
 'cool text head',
 'sent ur email id soon',
 'gorgeou keep pix cum thank',
 'storm msg wen u lift phne u say hello u knw wt real mean hello name girl ye u knw dat girl margaret hello girlfrnd f grahmbel invnt telphon moral one get name person bt girlfrnd g n g h',
 'yeah tri scroung someth',
 'messag great doctor india drink appi fizz contain cancer caus age',
 'thank princess want see nice juici booti',
 'uniqu user id remov send stop custom servic',
 'class hour sorri',
 'cant think anyon spare room top head',
 'know u u know send chat let find p msg rcvd hg suit land row w j hl ldn year',
 'home watch tv lor',
 'id onluy matter get offcampu',
 'see shadow get earli spring yay',
 'loan purpos homeown tenant welcom previous refus still help call free text back help',

In [21]:
len(corpus)

9650

In [22]:
len(corpus[10])

51

# TFIDF Approach

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
#from sklearn.pipeline import Pipeline

In [24]:
tfidf = TfidfVectorizer()

In [25]:
X_tfidf = corpus   # 1D Series
y_tfidf = data['Label']

In [26]:
print(X_tfidf)

['rememb', 'life mean lot love life love peopl life world call friend call world ge', 'e admin build might b slightli earlier call u reach', 'sorri went bed earli nightnight', 'new voicemail pleas call', 'urgent mobil number award prize guarante call land line claim valid hr ppm', 'camera award sipix digit camera call fromm landlin deliveri within day', 'nice day impress sensibl went home earli feel fine bore rememb', 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max', 'kindli send one flat lt decim gt today', 'hey darlin pick u colleg u tell wen mt love pete xx', 'mobil club choos top qualiti item mobil cfca', 'fyi gonna call sporad start like lt gt bc doin shit', 'realli tot ur paper end long ago wat u copi ju got use u happi lar still haf studi', 'know pl open back', 'wake sinc check stuff saw true avail space pl call embassi send mail', 'jokin lar depend phone father get lor', 'hi ami send free phone number coupl day give access adult parti', 'today offer claim ur worth discount voucher text ye savamob member offer mobil cs sub unsub repli x', 'hi jon pete ive bin spain recent hav sum dinero left bill said u ur rent mayb interest hav pe around tb jame', 'accordingli repeat text word ok mobil phone send', 'bloomberg messag center wait appli futur http career bloomberg com', 'costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min', 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg', 'poor girl go one day lmao', 'new textbuddi chat horni guy ur area p free receiv search postcod gaytextbuddi com txt one name', 'record indic u mayb entitl pound compens accid claim free repli claim msg stop txt stop', 'tkt euro cup final cash collect call b pobox ppm', 'forward hi mailbox messag sm alert match pleas call back retriev messag match cc p min', 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq', 'today voda number end select receiv award match pleas call quot claim code standard rate app', 'hot n horni will live local text repli hear strt back p per msg netcollex ltdhelpdesk repli stop end', 'send naughti pix', 'say bold torch later one torch bold', 'meet da call', 'welcom uk mobil date msg free give free call futur mg bill p daili cancel send go stop', 'lip sync shangela', 'urgent tri contact u today draw show prize guarante call land line claim j po box c pm', 'nokia tone ur mob everi week txt nok st tone free get txtin tell ur friend p tone repli hl info', 'winner u special select receiv cash holiday flight inc speak live oper claim', 'peopl dog area call join like mind guy arrang even minapn ls bb', 'awesom text restock', 'take derek amp taylor walmart back time done leav mous desk text priscilla readi', 'oh k placement ah', 'yeah sure thing mate haunt got stuff sort im go sound anyway promot hex way dont know number joke', 'took hooch walk toaday fell splat graze knee everyth stay home see tomorrow', 'haha think', 'come onlin today night', 'rington club gr new poli direct mobil everi week', 'home n readi', 'somewher beneath pale moon light someon think u dream come true goodnit amp sweet dream', 'ok wif co like tri new thing scare u dun like mah co u said loud', 'good luck draw take place th feb good luck remov send stop custom servic', 'rock yr chik get filthi film xxx pic yr phone rpli filth saristar ltd e yt p per day stop cancel', 'let know need anyth els salad desert someth mani beer shall get', 'urgent pleas call landlin complimentari lux costa del sol holiday cash await collect ppm sae cs jame eh rr', 'miss', 'next amaz xxx picsfre video sent enjoy one vid enough day text back keyword picsfre get next video', 'hello thanx take call got job start monday', 'way', 'motiv behind everi dark shine light wait find behind everi best friend alway trust love bslvyl', 'phoni award today voda number end xxxx select receiv award match pleas call quot claim code standard rate app', 'guarante cash prize claim yr prize call custom servic repres pm cost p', 'bear pic nick tom pete dick fact type tri gay chat photo upload call p min stop text call', 'love night wake see messag hope smile know great morn', 'import inform orang user xxxxxxx today lucki day find log onto http www urawinn com fantast surpris await', 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p', 'rgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max', 'cant pick phone right pl send messag', 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg', 'otherwis part time job na tuition', 'k best congrat', 'new messag call', 'urgent ur guarante award still unclaim call closingd claimcod pmmorefrommobil bremov mobypobox ls yf', 'babe lost', 'nope sinc ayo travel forgotten guy', 'urgent import inform user today lucki day find log onto http www urawinn com fantast surpris await', 'forward pleas call immedi urgent messag wait', 'abl sleep', 'free tarot text find love life tri free text chanc free msg', 'sir wait call', 'hope pee burn tonit', 'bore housew chat n date bt nation rate p min landlin', 'safe trip nigeria wish happi soon compani share moment', 'today offer claim ur worth discount voucher text ye savamob member offer mobil cs sub unsub repli x', 'alright see bit', 'pl send comprehens mail pay much', 'tag friend seem count friend', 'free entri weekli comp send word enter c www textcomp com cust care', 'goodmorn grandfath expir leav today', 'r u sam p eachoth meet go hous', 'oki', 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker', 'custom place call', 'ok', 'nah think goe usf live around though', 'check choos babe video sm shsex netun fgkslpopw fgkslpo', 'dear u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr', 'free text messag valid decemb', 'sm ac jsco energi high u may know channel day ur leadership skill r strong psychic repli an w question end repli end jsco', 'k k pa lunch aha', 'k leav soon littl', 'lt gt min stop somewher first', 'loan purpos homeown tenant welcom previous refus still help call free text back help', 'win shop spree everi week start play text store skilgm tsc winawk age perweeksub', 'check head drop stuff', 'urgent call landlin complimentari ibiza holiday cash await collect sae cs po box sk wp ppm', 'hard live chat p min choos girl connect live call cheap chat uk biggest live servic vu bcm wc n xx', 'thank love torch bold', 'time ur flight tmr', 'warner villag c colin farrel swat wkend warner villag get free med popcorn show msg ticket kiosk valid c c kiosk repli soni mre film offer', 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p', 'beauti truth graviti read care heart feel light someon feel heavi someon leav goodmorn', 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw', 'u r subscrib textcomp wkli comp st wk free question follow subsequ wk charg p msg unsubscrib txt stop custcar', 'boo thing back home littl bore alreadi', 'win year suppli cd store ur choic worth enter weekli draw txt music ts cs www ldew com sub win ppmx', 'gr poli tone mob direct u rpli poli titl eg poli breath titl crazyin sleepingwith finest ymca getz co uk pobox w wq p', 'oh god found number glad text back xafter msg cst std ntwk chg', 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg txtauction', 'gimm lt gt minut ago', 'nd time tri contact u u pound prize claim easi call p per minut bt nation rate', 'howz pain hope u r fine', 'k sure consent form v', 'dare chang ring', 'turn stereo love mi phone unknown album', 'free st week nokia tone ur mob everi week txt nokia get txting tell ur mate zed pobox w wq norm p tone', 'differ style', 'that cool want pleas', 'free unlimit hardcor porn direct mobil txt porn get free access hr chrgd p per day txt stop exit msg free', 'jay told alreadi', 'saturday sunday holiday difficult', 'send content page', 'account credit free text messag activ txt word credit cs www biz', 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate', 'surf onlin store offer want buy thing', 'guarante cash prize claim yr prize call custom servic repres pm cost p', 'go take bath ill place key window', 'nd attempt contract u week top prize either cash prize call', 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg txtauction', 'thank rington order refer number x mobil charg tone arriv pleas call custom servic colour red text colour txtstar', 'surli ill give come review', 'shop till u drop either k k cash travel voucher call ntt po box cr bt fixedlin cost ppm mobil vari', 'wherr boytoy', 'want new video phone anytim network min half price line rental free text month repli call free deliveri', 'didnt complet gist oh', 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli', 'hey babe go ever figur go new year', 'goal arsen henri v liverpool henri score simpl shot yard pass bergkamp give arsen goal margin min', 'wife knew time murder exactli', 'hi ibh custom loyalti offer new nokia mobil txtauction txt word start get', 'want new nokia colour phone deliv tomorrow free minut mobil free text free camcord repli call', 'twink bear scalli skin jock call miss weekend fun call p min stop text call nat rate', 'go write msg put dictionari mode cover screen hand press lt gt gentli remov ur hand interest', 'valu custom pleas advis follow recent review mob award bonu prize call', 'u nokia plu free digit camera u get u win free auction take part send nokia pobox tcr w', 'swhrt u dey hope ur ok tot u day love n miss take care', 'bore speed date tri speedchat txt speedchat like em txt swap get new chatter chat pobox w wq p msg rcd', 'ur chanc win wkli shop spree txt shop c www txt shop com custcar x p wk', 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate', 'siva hostel aha', 'v skint fanci bevi waz gona go meet othr spoon jst bin watchng planet earth sofa v comfey dont make hav gd night', 'network allow compani bill sm respons supplier shop give guarante sell b g', 'want anytim network min text new video phone five pound per week call repli deliveri tomorrow', 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q', 'could seen recognis face', 'hot live fantasi call p per min ntt ltd po box croydon cr wb nation rate call', 'free day sexi st georg day pic jordan txt pic dont miss everi wk sauci celeb pic c pocketbab co uk wk', 'fran decid go n e way im complet broke knacker got bout c u mrw love janx p dad fone credit', 'master buy bb co sale bf', 'dont use hook', 'sell ton coin sell coin someon thru paypal voila money back life pocket', 'date servic ask contact u someon shi call reveal pobox uz p', 'anyway go gym whatev love smile hope ok good day babe miss much alreadi', 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap', 'dhoni luck win big titl win', 'made eta taunton plan hope still okday good see xx', 'eastend tv quiz flower dot compar violet e tulip f lili txt e f chanc win cash wkent p', 'im good think', 'oki', 'ft good combin', 'pick receipt someth earlier', 'realli need kiss u miss u babi ur babi eva', 'urgent mobil award bonu caller prize nd attempt contact call box qu', 'sunshin quiz wkli q win top soni dvd player u know countri liverpool play mid week txt ansr sp tyron', 'mobil mth updat free orang latest colour camera mobil unlimit weekend call call mobil upd freefon stoptxt', 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free', 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd', 'even friend priest call', 'uncl abbey happi new year abiola', 'pleas protect e threat sib never ask sensit inform like password atm sm pin thru email never share password anybodi', 'hi happi birthday hi hi hi hi hi hi hi', 'remind download content alreadi paid goto http doit mymobi tv collect content', 'lord ring return king store repli lotr june chanc win lotr soundtrack cd stdtxtrate repli stop end txt', 'cashbin co uk get lot cash weekend www cashbin co uk dear welcom weekend got biggest best ever cash give away', 'tri call repli sm video mobil min unlimit text free camcord repli call', 'hey charl sorri late repli', 'current messag await collect collect messag call', 'yup havent want go yoga call book', 'yet chikku go room nw bu', 'yeah leav coupl minut amp let know get mu', 'urgent pleas call landlin abta complimentari tenerif holiday cash await collect sae cs box cw wx ppm', 'much buzi', 'privat account statement show un redeem point call identifi code expir', 'next amaz xxx picsfre video sent enjoy one vid enough day text back keyword picsfre get next video', 'prepar pound everi night', 'told hr want post chennai work', 'loan purpos homeown tenant welcom previous refus still help call free text back help', 'sex ur mobil free sexi pic jordan text babe everi wk get sexi celeb pocketbab co uk pic wk', 'loan purpos homeown tenant welcom previous refus still help call free text back help', 'head straight', 'send resum', 'ard like dat lor juz meet mrt station dun haf come', 'dear u invit xchat final attempt contact u txt chat', 'hope good week check', 'sm servic inclus text credit pl goto www comuk net login qxj unsubscrib stop extra charg help comuk cm ae', 'pay first lar da stock comin', 'winner u special select receiv holiday flight inc speak live oper claim p min', 'u look da lib got stuff havent finish yet', 'reciev tone within next hr term condit pleas see channel u teletext pg', 'hi ya babe x u goten bout scammer get smart though regular vodafon respond get prem rate msg subscript no use also bewar', 'releas anoth italian one today cosign option', 'pleas call custom servic repres pm guarante cash prize', 'guarante cash prize claim yr prize call custom servic repres pm', 'u haf keep busi', 'kit strip bill p netcollex ltd po box ig oja', 'yep great loxahatche xma tree burn lt gt start hour', 'well watch shrek b', 'congrat mobil g videophon r call videochat wid ur mate play java game dload polyh music nolin rentl bx ip pm', 'natalja f invit friend repli ye see www sm ac u nat stop send stop frnd', 'winner u special select receiv cash holiday flight inc speak live oper claim', 'privat account statement show un redeem point call identifi code expir', 'last chanc claim ur worth discount voucher today text shop savamob offer mobil cs savamob pobox uz sub', 'urgent nd attempt contact u u call b csbcm wc n xx callcost ppm mobilesvari max', 'block breaker come delux format new featur great graphic mobil buy repli get bbdelux take challeng', 'win cash prize prize worth', 'urgent tri contact u today draw show prize guarante call land line claim valid hr', 'guarante cash prize claim yr prize call custom servic repres pm cost p', 'hi chachi tri call u unabl reach u pl give miss cal u c tiz msg kanagu', 'lost help', 'free tone hope enjoy new content text stop unsubscrib help p provid tone co uk', 'dear xxxxxxx u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr', 'send yetti number pl', 'pleas call amanda regard renew upgrad current mobil handset free charg offer end today tel subject c', 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age', 'custom loyalti offer new nokia mobil txtauction txt word start get ctxt tc p mtmsg', 'sent send', 'remain unconvinc elabor test willpow', 'ye last practic', 'ok happen behav like', 'themob hit link get premium pink panther game new sugabab crazi zebra anim badass hoodi wallpap free', 'hello r u im bore inev thought id get bore tv tell someth excit happen anyth', 'still mayb leav credit card get ga get back like told', 'cmon babe make horni turn txt fantasi babe im hot sticki need repli cost cancel send stop', 'never believ actual got taunton wow', 'anyth lor u decid', 'alway chat fact need money rais', 'yeah probabl still gotta check leo', 'opinion jada kusruthi lovabl silent spl charact matur stylish simpl pl repli', 'hello boytoy geeee miss alreadi woke wish bed cuddl love', 'new tone week includ mcfli ab sara jorg shock smith switch order follow instruct next messag', 'see finish load loan pay', 'uniqu user id remov send stop custom servic', 'marri local women look discreet action real match instantli phone text match msg cost p stop txt stop bcmsfwc n xx', 'ok would b love u r sure think wot u want drinkin dancin eatin cinema u wot', 'privat account statement show un redeem point call identifi code expir', 'room', 'wan win meet greet westlif u current tour unbreak untam unkempt text cost p std text', 'sac score big hundr set batsman', 'free st week entri textpod chanc win gb ipod cash everi wk txt pod ts cs www textpod net custcar', 'say lt gt year old man money last lt gt still wait check', 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age', 'know result', 'nah perpetu dd', 'great role model give much realli wish day miracl god reason everyth must say wish knew dont look sinc young still great day', 'go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'chang fb jaykwon thuglyf falconerf', 'love start attract feel need everi time around first thing come thought would start day end everi time dream love everi breath name life happen around life name would cri give happi take sorrow readi fight anyon love craziest thing love proov anyon girl beauti ladi whole planet alway sing prais love start make chicken curri end maki sambar life beauti get everi morn thank god day would like say lot tell later', 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi', 'come peopl', 'haha figur well found piec priscilla bowl', 'dunno juz askin co got card got salon call hair sens tot da one cut ur hair', 'shop till u drop either k k cash travel voucher call ntt po box cr bt fixedlin cost ppm mobil vari', 'freemsg txt call claim reward hour talk time use phone subscrib gbp mnth inc hr stop txtstop', 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw', 'lol well without could big sale togeth', 'want new nokia colour phone deliveredtomorrow free minut mobil free text free camcord repli call', 'dunno lei thk mum lazi go neva ask yet', 'hey elain today meet still', 'dunno lei like dun haf', 'themob yo yo yo come new select hot download member get free click open next link sent ur fone', 'cool text head', 'sent ur email id soon', 'gorgeou keep pix cum thank', 'storm msg wen u lift phne u say hello u knw wt real mean hello name girl ye u knw dat girl margaret hello girlfrnd f grahmbel invnt telphon moral one get name person bt girlfrnd g n g h', 'yeah tri scroung someth', 'messag great doctor india drink appi fizz contain cancer caus age', 'thank princess want see nice juici booti', 'uniqu user id remov send stop custom servic', 'class hour sorri', 'cant think anyon spare room top head', 'know u u know send chat let find p msg rcvd hg suit land row w j hl ldn year', 'home watch tv lor', 'id onluy matter get offcampu', 'see shadow get earli spring yay', 'loan purpos homeown tenant welcom previous refus still help call free text back help', 'watch lotr w si di aft u wan meet dinner nite', 'eeri nokia tone u rpli tone titl eg tone dracula titl ghost addamsfa munster exorcist twilight www getz co uk pobox w wq p', 'offic around pm go hospit', 'free video camera phone half price line rental mth cross ntwk min txt call mobileupd call optout', 'ok april cant wait', 'camera award si

In [27]:
print(type(X_tfidf))

<class 'list'>

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y_tfidf,
    test_size=0.2,
    random_state=42,
    stratify=y_tfidf   # important for imbalanced spam dataset
)

In [29]:
X_train_tfidf = tfidf.fit_transform(X_train)

In [30]:
X_test_tfidf = tfidf.transform(X_test)

In [31]:
from sklearn.naive_bayes import MultinomialNB

nb_1 = MultinomialNB(alpha=1.0)
nb_1.fit(X_train_tfidf, y_train)

MultinomialNB()

In [32]:
y_train_pred = nb_1.predict(X_train_tfidf)

In [33]:
y_train

6993    spam
2629     ham
4078     ham
2779     ham
1879     ham
        ...
4640    spam
6731     ham
983      ham
532      ham
7775     ham
Name: Label, Length: 7720, dtype: object

In [34]:
y_pred_test = nb_1.predict(X_test_tfidf)

In [35]:
y_pred_test

array(['spam', 'ham', 'spam', ..., 'ham', 'spam', 'spam'], dtype='<U4')

In [36]:
y_test

6383    spam
6523     ham
8357    spam
2432    spam
3137     ham
        ...
8575     ham
6499     ham
8378     ham
1801    spam
3366    spam
Name: Label, Length: 1930, dtype: object

In [37]:
df_predict= pd.DataFrame({"y_test":y_test,"y_pred_test":y_pred_test})
df_predict.head()

     y_test y_pred_test
6383   spam        spam
6523    ham         ham
8357   spam        spam
2432   spam        spam
3137    ham         ham

In [38]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_train, y_train_pred))
print()
print("*****************"*5)
print(classification_report(y_train, y_train_pred))

Accuracy: 0.9856217616580311

*************************************************************************************
              precision    recall  f1-score   support

         ham       0.99      0.98      0.99      3860
        spam       0.98      0.99      0.99      3860

    accuracy                           0.99      7720
   macro avg       0.99      0.99      0.99      7720
weighted avg       0.99      0.99      0.99      7720

In [39]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_test))
print()
print("**********"*5)
print(classification_report(y_test, y_pred_test))

Accuracy: 0.9787564766839378

**************************************************
              precision    recall  f1-score   support

         ham       0.99      0.97      0.98       965
        spam       0.97      0.99      0.98       965

    accuracy                           0.98      1930
   macro avg       0.98      0.98      0.98      1930
weighted avg       0.98      0.98      0.98      1930

print(X_bow.shape)
print(X_tfidf.shape)

X_bow.toarray()[0]
X_tfidf.toarray()[0]

# Step 1 — After Training, Create Prediction Function

In [40]:
import re

def preprocess_text(text):
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    text = ' '.join(text)
    return text

# Step 2 — Predict New Email

In [41]:
def predict_email(email_text):
    # Step 1: Clean
    cleaned_text = preprocess_text(email_text)

    # Step 2: Vectorize (transform only!)
    vector = tfidf.transform([cleaned_text])

    # Step 3: Predict
    prediction = nb_1.predict(vector)[0]

    if prediction == 1:
        return "Spam"
    else:
        return "Ham"

# Example Usage

In [42]:
new_mail = "Hello PANKAJ SHARMA,Thank you for registering for PC AIML - Machine Learning. You can find information about this meeting below.PC AIML - Machine Learning"

print(predict_email(new_mail))

Ham

In [43]:
new_mail = 'urgent tri contact u today draw show prize guarante call land line claim c valid hr'

print(predict_email(new_mail))

Ham

In [44]:
new_mail = "Hello! Pankaj can you come tomorrow for urgent meeting"

print(predict_email(new_mail))

Ham

In [45]:
new_mail = "Congratulation!Pankaj you won a prize."

print(predict_email(new_mail))

Ham

| Step               | Manual Cleaning | Vectorizer     |
| ------------------ | --------------- | -------------- |
| Lowercase          | Yes             | Yes            |
| Remove punctuation | Yes             | Yes            |
| Remove stopwords   | Yes             | Yes (optional) |
| Stemming           | Yes             | No             |
| Needed for BOW?    | ❌ No            |                |
| Needed for TF-IDF? | ❌ No            |                |

# While need to save the model you should use concept of pipe line

| Action           | Recommendation |
| ---------------- | -------------- |
| Oversampling     | ❌ No           |
| Keep imbalance   | ✅ Yes          |
| Use stratify     | ✅ Absolutely   |
| Evaluate with F1 | ✅ Yes          |